# .lychee.toml
exclude = [
  "https://instagram.com/*",
  "https://www.instagram.com/*",
  "https://www.tiktok.com/*",
  "https://open.spotify.com/*"
]
exclude_mail = true

# Treat GitHub Pages–style absolute paths as local
# (lychee will resolve ./assets etc. from repo root)
scheme = "https"

# Retry transient network issues
max_retries = 3
retry_wait_time = 2

# Timeouts (seconds)
timeout = 20

# Fail on 4xx/5xx for other links
fail = "error"

# Check local files (HTML/markdown) plus external links (minus excludes)
# You can add more globs if you add docs later.
